{
 "title": "MassTransit - Messages Monitoring from OTEL Collector",
 "description": "MassTransit is a message-based distributed application framework for .NET http://masstransit-project.com.\r\n\r\nMassTransit supports Prometheus metric capture, which provides useful observability into the bus, endpoints, consumers, and messages.\r\n\r\nThis dashboard shows the messages published and sent using MassTransit framework.",
 "tags": [
  "MassTransit",
  "Event Driven Architecture"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(exported_job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(exported_instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "MessageType",
    "label": "Message Type",
    "query": {
     "query": "label_values(messaging_masstransit_message_type)"
    }
   },
   {
    "name": "SagaType",
    "query": {
     "query": "label_values(mt_saga_in_progress,consumer_type)"
    }
   },
   {
    "name": "SagaMessageType",
    "query": {
     "query": "label_values(mt_saga_in_progress,messaging_masstransit_message_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages Sent/Published (Commands/Events)",
   "type": "table",
   "description": "Commands are objects sent direct to an endpoint and will be picked up by the first consumer that implements it. It means that something must be performed after receiving that message.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(messaging_masstransit_send_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Consumed",
   "type": "table",
   "description": "Total number of messages consumed",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(messaging_masstransit_consume_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__range])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Producers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Send Total",
   "type": "stat",
   "description": "Total number of messages sent (one to one commands)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(messaging_masstransit_send_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Send Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_send_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Send Fault Total",
   "type": "stat",
   "description": "Total number of message send faults",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(messaging_masstransit_send_errors_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Send Fault Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_send_errors_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consume Total",
   "type": "stat",
   "description": "Total number of messages consumed",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_masstransit_consume_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consume Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_consume_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consume Fault Total",
   "type": "stat",
   "description": "Total number of message consume faults",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_masstransit_consume_errors_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consume Fault Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_consume_errors_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consume endpoints total",
   "type": "stat",
   "description": "Number of receive endpoint instances.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mt_endpoint{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"})"
    }
   ]
  },
  {
   "title": "Consumers in progress",
   "type": "stat",
   "description": "Number of consumers in progress",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_masstransit_consume_active_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consume Retry Total",
   "type": "stat",
   "description": "Total number of message consume retries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_masstransit_consume_retries_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consume Retry Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(messaging_masstransit_consume_retries_ea_total{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consume Duration (ms)",
   "type": "timeseries",
   "description": "Elapsed time spent consuming a message, in seconds.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_masstransit_consume_duration_milliseconds_bucket{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__rate_interval])) by (messaging_masstransit_message_type,le))  ",
     "legendFormat": "{{messaging_masstransit_message_type}}"
    }
   ]
  },
  {
   "title": "Delivery Duration (ms)",
   "type": "timeseries",
   "description": "Elapsed time between when the message was sent and when it was consumed, in seconds.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_masstransit_delivery_duration_milliseconds_bucket{exported_job=\"$job\",exported_instance=~\"$instance\",messaging_masstransit_message_type=~\"$MessageType\"}[$__rate_interval])) by (messaging_masstransit_message_type,le))",
     "legendFormat": "{{messaging_masstransit_message_type}}"
    }
   ]
  }
 ]
}